### ISSUE TITLE
Kotlin | Configurable Android device

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#133]
`TestRunner.kt#L54-L59`

```kotlin
val androidMatrix = GcAndroidMatrix.build( 
         "NexusLowRes", 
         "26", 
         "en", 
         "portrait") 
```

Users should be able to specify the device to use in the Yaml Config.

requires: https://github.com/TestArmada/flank/issues/187

the format should follow the gcloud CLI style for device specification

`--device=DIMENSION=VALUE,[…]`
https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run

```bash
# gcloud cli example
 --device model=NexusLowRes,orientation=landscape
 --device model=shamu,version=21,locale=fr
```

```yaml
# yaml example
devices:
  - shamu:
      version: 21
      locale: fr
```

**Comment by yogurtearl** [comment]
We can support this using a Yaml list of objects.

Will need to provide the same info as the `--device` option on the gcloud CLI
https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run

Both of these syntaxes should work: 

```yaml
devices:
  - { model: Nexus6 }
  - { version: 23, orientation: landscape }
  - { model: shamu, version: 22, locale: zh_CN, orientation: default }
```

```yaml
devices:
  - model: Nexus6
  - version: 23
    orientation: landscape 
  - model: shamu
    version: 22
    locale: zh_CN
    orientation: default
```
