### ISSUE TITLE
flank should be optional in flank.yml

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/flank#310]
```
gcloud:
  app: ../outputs/apk/debug/app-debug.apk
  test: ../outputs/apk/androidTest/debug/app-debug-androidTest.apk
  project: flank-gradle
```

crashes doctor command because `flank:` is missing.

----

run command fails on:

```
gcloud:
  app: ../outputs/apk/debug/app-debug.apk
  test: ../outputs/apk/androidTest/debug/app-debug-androidTest.apk
  project: flank-gradle

flank:
```
