### ISSUE TITLE
Add option to specify apks in device section of flank.yml

### ISSUE THREAD

**Issue by rpappalax** [TestArmada/flank#347]
If I understand correctly, currently you can specify different devices in one flank.yml, however, all of those will be associated with the same apks defined in the (global) "app:" and "test:" sections.

While we do test across multiple devices, we also push our arm and X86 builds onto different devices for testing.  It seems like it would be more flexible to be able to override the global values specified above by specifying alternate apks directly in the device section.

Something like:
```
device:
   - model: Nexus6P
     version: 23
     app: ./app/build/output/apk/demoX86/debug/app-demo-x86-debug.apk
     test: ./app/build/output/apk/androidTest/demoX86/debug/app-demo-x86-debug-androidTest.apk
   - model: Pixel2
     version: 26
     app: ./app/build/output/apk/demoarm/debug/app-demo-arm-debug.apk
     test: ./app/build/output/apk/androidTest/demoX86/debug/app-demo-arm-debug-androidTest.apk
```
