### ISSUE TITLE
new yaml-config throws permission error for gcloud storage bucket -> old config is working

### ISSUE THREAD

**Issue by andreschab90** [TestArmada/flank#529]
`Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (ftl.cli.firebase.test.android.AndroidRunCommand@70efb718): com.google.cloud.storage.StorageException: xxx@yyy.com does not have storage.buckets.list access to project 1234.`

`Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "xxx@yyy.com does not have storage.buckets.list access to project 1234.",
    "reason" : "forbidden"
  } ],
  "message" : "xxx@yyy.com does not have storage.buckets.list access to project 1234."
}`

***old yaml config***
```yaml
gcloud:
  results-bucket: 123
  results-dir: build-$BITRISE_BUILD_NUMBER
  record-video: true
  timeout: 30m
  async: false
  project: 1234
  results-history-name: xxx
  flaky-test-attempts: 1
  app: $BITRISE_APK_PATH
  test: $BITRISE_TEST_APK_PATH
  auto-google-login: false
  use-orchestrator: true
  environment-variables:
    clearPackageData: true
  performance-metrics: true
  device:
  - model: walleye
    version: 28
    locale: en
    orientation: portrait

flank:
  testShards: 8
  shardTime: -1
  repeatTests: 1
  smartFlankGcsPath: gs://xxx/yyy/results.xml
  disableSharding: false
```

***new yaml config***
```yaml
gcloud:
  results-bucket: 123
  results-dir: build-$BITRISE_BUILD_NUMBER
  record-video: true
  timeout: 30m
  async: false
  results-history-name: xxx
  flaky-test-attempts: 1
  app: $BITRISE_APK_PATH
  test: $BITRISE_TEST_APK_PATH
  auto-google-login: false
  use-orchestrator: true
  environment-variables:
    clearPackageData: true
  performance-metrics: true
  device:
  - model: walleye
    version: 28
    locale: en
    orientation: portrait

flank:
  max-test-shards: 8
  shard-time: -1
  repeat-tests: 1
  smart-flank-gcs-path: gs://xxx/yyy/results.xml
  disable-sharding: false
  project: 1234
```
